name: Go build
#
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
#
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.20.x', '1.21.x', '1.22.x', '1.23.x'  ]
    steps:
    - uses: actions/checkout@v3
    #
    - name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
        cache: true
    #
    - name: Build Go
      run: go build -v ./...
    #