env:
  ACTIONS_STEP_DEBUG: true
#
on:
  release:
    types: [published]
#
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    #
    steps:
    - uses: actions/checkout@v4
    #
    - name: Setup Go 
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.1
        cache: true
    #
    - name: Build dockerlint ai binary
      id: build-go-docker-ai
      shell: bash
      run: |
          sudo sh build.sh 
    #
    - name: Upload go-docker-ai 
      uses: actions/upload-artifact@v4
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        name: upload-go-docker-ai
        path: /tmp/bin/go-docker-ai.tar.gz
    #
    - name: Release go-docker-ai
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        body: "# Release ${{github.ref}} \n"
        files: |
          LICENSE
          /tmp/bin/go-docker-ai.tar.gz